const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),KEY="100seconds_v4";
let d=JSON.parse(localStorage.getItem(KEY)||'{"best":0,"coins":250,"games":0,"earned":0,"maxCombo":1,"xp":0,"daily":{"date":"","best":0},"items":{"shield":0,"turbo":0,"double":0}}');
function today(){return new Date().toISOString().slice(0,10)}function save(){localStorage.setItem(KEY,JSON.stringify(d));refresh()}
function refresh(){let l=Math.floor(d.xp/500)+1;$("#best").textContent=d.best;$("#coins").textContent=d.coins;$("#level").textContent=l;$("#shopCoins").textContent=d.coins;$("#sGames").textContent=d.games;$("#sBest").textContent=d.best;$("#sCoins").textContent=d.earned;$("#sCombo").textContent="x"+d.maxCombo;$("#sLevel").textContent=l;$("#xpBar").style.width=((d.xp%500)/5)+"%";$("#dailyBadge").textContent=d.daily.date===today()?d.daily.best:0;$("#dbest").textContent=d.daily.date===today()?d.daily.best:0;$("#rank").textContent=l<3?"Débutant":l<6?"Confirmé":l<10?"Expert":"Légende"}
function screen(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");refresh();if(id==="shop")renderShop()}
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1300)}
function particles(ok=true){for(let i=0;i<18;i++){let p=document.createElement("i");p.className="particle";p.style.left="50%";p.style.top="50%";p.style.background=ok?["#27d7ff","#7c5cff","#ff4fa3","#62f5c4"][i%4]:"#ff6f9f";p.style.setProperty("--x",(Math.random()*260-130)+"px");p.style.setProperty("--y",(Math.random()*220-110)+"px");$("#fx").appendChild(p);setTimeout(()=>p.remove(),750)}}
function celebrate(ok){particles(ok);$("#game").classList.remove("shake","flash");void $("#game").offsetWidth;$("#game").classList.add(ok?"flash":"shake")}
$$("[data-screen]").forEach(b=>b.onclick=()=>screen(b.dataset.screen));function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
const colors=[["🔴","#ff4f64"],["🔵","#27a9ff"],["🟢","#35df8b"],["🟡","#ffd44d"],["🟣","#a66cff"],["🟠","#ff8c42"]];
function numeric(q,a){let v=[a,a+rand(1,3),a-rand(1,3),a+rand(4,7)];v=[...new Set(v)];while(v.length<4)v.push(a+v.length+5);v.sort(()=>Math.random()-.5);return{type:"CALCUL",html:`<div class="q">${q}</div><div class="choices">${v.map(x=>`<button class="choice" data-v="${x}">${x}</button>`).join("")}</div>`,answer:a}}
const makers=[
()=>{let a=rand(2,12),b=rand(2,12);return numeric(`${a} + ${b} = ?`,a+b)},
()=>{let a=rand(3,12),b=rand(2,9);return numeric(`${a} × ${b} = ?`,a*b)},
()=>{let a=rand(20,90),b=rand(2,15);return numeric(`${a} − ${b} = ?`,a-b)},
()=>{let n=rand(100,999),ans=String(n).split("").reverse().join("");return{type:"MÉMOIRE",html:`<div class="q">Mémorise ce nombre</div><div class="sequence">${String(n).split("").map(x=>`<i class="tile">${x}</i>`).join("")}</div><div class="sub">Il disparaît...</div>`,answer:ans,memory:true}},
()=>{let step=rand(2,7),start=rand(1,15),seq=[start,start+step,start+step*2,start+step*3];return numeric(`${seq.slice(0,3).join(" • ")} • ?`,seq[3])},
()=>{let c=[...colors].sort(()=>Math.random()-.5),target=c[rand(0,c.length-1)];return{type:"COULEUR",html:`<div class="q">Trouve ${target[0]}</div><div class="colorGrid">${c.slice(0,4).map(x=>`<button class="colorBtn" style="background:${x[1]}" data-v="${x[0]}"></button>`).join("")}</div>`,answer:target[0]}},
()=>{let arrow=["↑","→","↓","←"][rand(0,3)],vals=["↑","→","↓","←"].sort(()=>Math.random()-.5);return{type:"RÉFLEXE",html:`<div class="q">Trouve ${arrow}</div><div class="arrowGrid">${vals.map(x=>`<button class="arrow" data-v="${x}">${x}</button>`).join("")}</div>`,answer:arrow}},
()=>{let vals=Array.from({length:9},()=>rand(1,6)),target=rand(1,6),idx=vals.findIndex(x=>x===target);if(idx<0){vals[0]=target;idx=0}return{type:"INTRUS",html:`<div class="q">Trouve le chiffre ${target}</div><div class="oddGrid">${vals.map((x,i)=>`<button class="odd" data-v="${i}">${x}</button>`).join("")}</div>`,answer:idx}},
()=>{let n=rand(2,5);return{type:"TAP",html:`<div class="q">Tape exactement ${n} fois</div><button class="tap" id="tap">TAP !</button><div class="tapCount" id="tapCount">0 / ${n}</div>`,answer:n,taps:true}},
()=>{let goal=rand(30,70);return{type:"PRÉCISION",html:`<div class="q">Arrête dans la zone</div><div class="target"><i id="cursor" style="left:${rand(0,90)}%"></i></div><input class="slider" id="slider" type="range" min="0" max="100" value="50"><div class="sub">Zone cible : ${goal-8}–${goal+8}</div>`,answer:goal,precision:true}},
()=>{let n=rand(3,5),seq=Array.from({length:n},()=>rand(0,1));return{type:"MÉMOIRE",html:`<div class="q">Mémorise les points</div><div class="memory">${seq.map(x=>`<i class="memDot ${x?"on":""}"></i>`).join("")}</div>`,answer:seq.filter(Boolean).length,delayed:true}},
()=>{let a=rand(1,9),b=rand(1,9);return numeric(`${a} × ? = ${a*b}`,b)},
()=>{let a=rand(10,30),b=rand(2,8),c=rand(1,5),ans=a+b*c;return numeric(`${a} + ${b} × ${c} = ?`,ans)}
];
let G={};
function start(mode="normal"){clearInterval(G.int);G={score:0,combo:d.items.turbo?2:1,left:100,mode,count:0,usedShield:false,max:1,locked:false};screen("game");$("#gscore").textContent=0;$("#gcombo").textContent="x"+G.combo;$("#gtimer").textContent=100;$("#meter").style.width="100%";next();G.int=setInterval(()=>{G.left--;$("#gtimer").textContent=G.left;$("#meter").style.width=G.left+"%";if(G.left<=0)finish()},1000)}
function next(){if(G.left<=0)return;G.count++;G.locked=false;$("#count").textContent=G.count;let c=makers[rand(0,makers.length-1)](),el=$("#challenge");$("#type").textContent=c.type;el.innerHTML=c.html;
if(c.delayed){setTimeout(()=>{if(G.left<=0)return;el.innerHTML=`<div class="q">Combien de points ?</div><div class="choices">${[0,1,2,3,4,5].map(x=>`<button class="choice" data-v="${x}">${x}</button>`).join("")}</div>`;$$(".choice").forEach(b=>b.onclick=()=>answer(b.dataset.v,c.answer))},650)}
else if(c.memory){setTimeout(()=>{el.innerHTML=`<div class="q">Quel était le nombre inversé ?</div><div class="choices">${[c.answer,c.answer.split("").reverse().join(""),c.answer.slice(0,-1),c.answer+"7"].map(x=>`<button class="choice" data-v="${x}">${x}</button>`).join("")}</div>`;$$(".choice").forEach(b=>b.onclick=()=>answer(b.dataset.v,c.answer))},850)}
else if(c.taps){let n=0,btn=$("#tap"),counter=$("#tapCount");btn.onclick=()=>{if(G.locked)return;n++;counter.textContent=`${n} / ${c.answer}`;if(n>=c.answer)answer(n,c.answer)}}
else if(c.precision){let sl=$("#slider"),cur=$("#cursor");sl.oninput=()=>cur.style.left=sl.value+"%";let submit=document.createElement("button");submit.className="primary";submit.textContent="VALIDER";submit.onclick=()=>answer(Number(sl.value),c.answer);el.appendChild(submit)}
else{$$(".choice").forEach(b=>b.onclick=()=>answer(b.dataset.v,c.answer))}}
function answer(v,a){if(G.locked)return;G.locked=true;let ok=Math.abs(Number(v)-Number(a))<=0;if(ok){G.score+=10*G.combo;G.combo=Math.min(12,G.combo+1);G.max=Math.max(G.max,G.combo);feedback("✓ PARFAIT",true)}else if(d.items.shield&&!G.usedShield){G.usedShield=true;feedback("🛡️ BOUCLIER UTILISÉ",true)}else{G.combo=1;feedback("✕ RATÉ",false)}$("#gscore").textContent=G.score;$("#gcombo").textContent="x"+G.combo;celebrate(ok);setTimeout(()=>{if(G.left>0)next()},210)}
function feedback(t,g){let x=$("#feedback");x.textContent=t;x.className="feedback "+(g?"good":"bad")}
function finish(){clearInterval(G.int);let old=d.best;d.games++;d.maxCombo=Math.max(d.maxCombo,G.max);let gain=Math.max(5,Math.floor(G.score/22));if(d.items.double)gain*=2;d.coins+=gain;d.earned+=gain;d.xp+=Math.max(10,G.score);if(G.score>d.best)d.best=G.score;if(G.mode==="daily"){if(d.daily.date!==today())d.daily={date:today(),best:G.score};else d.daily.best=Math.max(d.daily.best,G.score)}save();$("#resultScore").textContent=G.score;$("#earned").textContent=gain;$("#rCombo").textContent="x"+G.max;$("#rChallenges").textContent=G.count;$("#newRecord").innerHTML=G.score>old?'<span class="new">🏆 NOUVEAU RECORD</span>':"";$("#resultIcon").textContent=G.score>old?"🏆":"⚡";$("#resultLabel").textContent=G.mode==="daily"?"DÉFI DU JOUR":"PARTIE TERMINÉE";screen("result");if(G.score>old)particles(true)}
$("#play").onclick=()=>start();$("#replay").onclick=()=>start();$("#quit").onclick=()=>{clearInterval(G.int);screen("home")};
$("#daily").onclick=()=>{let names=["Réflexes express","Calcul éclair","Mémoire flash","Défi précision","Logique minute"];let n=new Date().getDate()%names.length;$("#dailyTitle").textContent=names[n];$("#dailyDesc").textContent="Une partie spéciale par jour. Améliore ton record et accumule de l'XP.";screen("dailyScreen")};$("#dailyPlay").onclick=()=>start("daily");
const shops=[["shield","🛡️","Bouclier","Protège une erreur",100],["turbo","🔥","Turbo","Commence chaque partie à x2",150],["double","💎","Double pièces","Double les récompenses",250]];
function renderShop(){$("#shopItems").innerHTML=shops.map(x=>`<article class="item"><div class="itemIcon">${x[1]}</div><div><h3>${x[2]}</h3><p>${x[3]} · Possédé : ${d.items[x[0]]}</p></div><button data-buy="${x[0]}" ${d.coins<x[4]?"disabled":""}>🪙 ${x[4]}</button></article>`).join("");$$("[data-buy]").forEach(b=>b.onclick=()=>{let x=shops.find(a=>a[0]===b.dataset.buy);if(d.coins>=x[4]){d.coins-=x[4];d.items[x[0]]++;save();renderShop();toast("Bonus acheté !")}})}
refresh();renderShop();